Vagrant.configure(2) do |config|
  	config.vm.box = "martyV/centos9-stream"

  # Kubernetes API Access
  config.vm.network "forwarded_port", guest: 6443, host: 6443


	config.vm.define "hrazanamS" do |controlS|
		controlS.vm.hostname = "hrazanamS"
		controlS.vm.network "private_network", ip: "192.168.56.110"
		controlS.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "2048" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      			v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "hrazanamS"]
		end
		config.vm.provision :shell, :inline =>  <<-SHELL
		  sudo yum -y install net-tools telnet 
		  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		  sudo systemctl restart sshd
		  sudo systemctl disable firewalld --now
		  curl -sfL https://get.k3s.io/ | sh -s - --write-kubeconfig-mode 644 --node-ip 192.168.56.110  --bind-address=192.168.56.110 --advertise-address=192.168.56.110
		  sudo echo "alias k=/usr/bin/kubectl" >> /home/vagrant/.bashrc
		  sudo systemctl start k3s
		  sudo echo "alias k=/usr/local/bin/kubectl" >> /home/vagrant/.bashrc
		  SHELL
		controlS.vm.provision "shell", path: "scripts/start_pods.sh"
	end
end
