Vagrant.configure(2) do |config|
  	config.vm.box = "martyV/centos9-stream"

	config.vm.define "hrazanamS" do |controlS|
		controlS.vm.hostname = "hrazanamS"
		controlS.vm.network "private_network", bridge: "enp0s8", ip: "192.168.56.110" 
		controlS.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "2048" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "hrazanamS"]
		end
		controlS.vm.provision :shell, :inline =>  <<-SHELL
		  sudo yum -y install net-tools 
		  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		  sudo systemctl restart sshd
		  sudo systemctl disable firewalld --now
		  curl -sfL https://get.k3s.io/ | sh -s - --write-kubeconfig-mode 644 --node-ip 192.168.56.110  --bind-address=192.168.56.110 --advertise-address=192.168.56.110
		  sudo echo "alias k=/usr/local/bin/kubectl" >> /home/vagrant/.bashrc
		  sudo systemctl start k3s
	 	  sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/
		  SHELL
	end

	config.vm.define "hrazanamSW" do |controlSW|
		controlSW.vm.hostname = "hrazanamSW"
		controlSW.vm.network "private_network", bridge:"enp0s8", ip: "192.168.56.111"
		controlSW.vm.provider "virtualbox" do |v|
			v.customize [ "modifyvm", :id, "--cpus", "2" ]
			v.customize [ "modifyvm", :id, "--memory", "1024" ]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--name", "hrazanamSW"]
		end
		controlSW.vm.provision :shell, :inline => <<-SHELL
		  sudo yum -y install net-tools telnet 
		  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		  sudo systemctl restart sshd
		  sudo systemctl disable firewalld --now
		  curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN_FILE="/vagrant/node-token" INSTALL_K3S_EXEC="--node-ip=192.168.56.111" sh -
		  sudo echo "alias k=/usr/local/bin/kubectl" >> /home/vagrant/.bashrc
		  SHELL
	end
end
